version: '3.1'
services:
  mysql_anika:
    container_name: mysql_anika
    image: mysql
    volumes:
      - "./.mysql/db_post:/var/lib/mysql"
    restart: always
    ports:
      - 3307:3306
    environment: 
      - MYSQL_ROOT_PASSWORD= null
      - MYSQL_USER=anika
      - MYSQL_PASSWORD=anika
      - MYSQL_DATABASE=db_post
    
     
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - mysql_anika
    environment: 
      - USERNAME=anika
      - PASSWORD=anika
      - HOST=mysql_anika
      - DATABASE=db_post