version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - "./.mysql/db_post:/var/lib/mysql"
    restart: always
    ports:
      - 3307:3306
    environment: 
      - MYSQL_ROOT_PASSWORD= null
    
     
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - mysql
    links:
      - mysql